# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [57]:
import os
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [58]:
baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv")
baby_names.head()

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

### Step 4. See the first 10 entries

In [59]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [60]:
# deletes Unnamed: 0
del baby_names['Unnamed: 0']

# deletes Unnamed: 0
del baby_names['Id']

baby_names.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

In [61]:
baby_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 5 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Name    1016395 non-null  object
 1   Year    1016395 non-null  int64
 2   Gender  1016395 non-null  object
 3   State   1016395 non-null  object
 4   Count   1016395 non-null  int64
dtypes: int64(2), object(3)
memory usage: 38.8+ MB

### Step 6. Is there more male or female names in the dataset?

In [62]:
n_female = baby_names[baby_names['Gender'] == 'F'].shape[0]
n_male = baby_names[baby_names['Gender'] == 'M'].shape[0]

print("Female: {} ---- Male: {}".format(n_female, n_male))

if n_female > n_male:
    print("Female is more than Male")
else:
    print("Male is more than Female")


##baby_names['Gender'].value_counts()

Female: 558846 ---- Male: 457549
Female is more than Male

### Step 7. Group the dataset by name and assign to names

In [63]:
# you don't want to sum the Year column, so you delete it
del baby_names["Year"]

# group the data
names = baby_names.groupby("Name").sum()

# print the first 5 observations
names.head()

# print the size of the dataset
print(names.shape)

# sort it from the biggest value to the smallest one
names.sort_values("Count", ascending = 0).head()

(17632, 3)

,Gender,State,Count
Name,,,
Jacob,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,242874
Emma,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,214852
Michael,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,214405
Ethan,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,209277
Isabella,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,204798

In [66]:
type(names)

pandas.core.frame.DataFrame

### Step 8. How many different names exist in the dataset?

In [64]:
# as we have already grouped by the name, all the names are unique already. 
# get the length of names
len(names)

17632

### Step 9. What is the name with most occurrences?

In [70]:
names.Count.idxmax()

'Jacob'

### Step 10. How many different names have the least occurrences?

In [77]:
names.Count.sort_values(ascending= True)[:3]

Name
Destenie    5
Janisha     5
Lizvet      5
Name: Count, dtype: int64

In [83]:
names.Count.min()

5

In [85]:
names[names.Count == 5]

         Gender State  Count
Name
Aadarsh       M    IL      5
Aadin         M    TX      5
Aaima         F    NY      5
Aalaya        F    CA      5
Aaminah       F    CA      5
...         ...   ...    ...
Zyien         M    TX      5
Zyire         M    NY      5
Zykeriah      F    AL      5
Zykierra      F    GA      5
Zymari        M    NC      5

[2578 rows x 3 columns]

### Step 11. What is the median name occurrence?

In [86]:
names.Count.median()

49.0

In [91]:
names[names.Count == 49]

           Gender             State  Count
Name
Aishani   FFFFFFF    CACACACACAILNJ     49
Alara    FFFFFFFF  CACACAFLNYNYNYTX     49
Alysse   FFFFFFFF  CACACAMINYTXTXTX     49
Ameir    MMMMMMMM  CAMIMIMIMIMINYOH     49
Anely    FFFFFFFF  CACACACACACACACA     49
...           ...               ...    ...
Sriram    MMMMMMM    CACACACACACATX     49
Trinton  MMMMMMMM  FLLAOKTXTXTXTXTX     49
Vita      FFFFFFF    CACACACACANYNY     49
Yoni     MMMMMMMM  CACACACACACAFLFL     49
Zuleima   FFFFFFF    AZCACACACACACA     49

[66 rows x 3 columns]

### Step 12. What is the standard deviation of names?

In [92]:
names.Count.std()

11006.06946789057

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [93]:
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000