# Fictitious Names

### Introduction:

This time you will create a data again 

Special thanks to [Chris Albon](http://chrisalbon.com/) for sharing the dataset and materials.
All the credits to this exercise belongs to him.  

In order to understand about it go [here](https://blog.codinghorror.com/a-visual-explanation-of-sql-joins/).

### Step 1. Import the necessary libraries

In [1]:
import os
import pandas as pd
import numpy as np

### Step 2. Create the 3 DataFrames based on the following raw data

In [2]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

### Step 3. Assign each to a variable called data1, data2, data3

In [3]:
data1 = pd.DataFrame(raw_data_1, columns = ['subject_id', 'first_name', 'last_name'])
data2 = pd.DataFrame(raw_data_2, columns = ['subject_id', 'first_name', 'last_name'])
data3 = pd.DataFrame(raw_data_3, columns = ['subject_id','test_id'])

data3

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

### Step 4. Join the two dataframes along rows and assign all_data

In [4]:
all_data = pd.concat([data1, data2])

all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

### Step 5. Join the two dataframes along columns and assing to all_data_col

In [5]:
all_data_col = pd.concat([data1, data2], axis=1)

all_data_col

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

### Step 6. Print data3

In [6]:
data3

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [7]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  10 non-null     object
 1   test_id     10 non-null     int64
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes

In [8]:
data3.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [10]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  10 non-null     object
 1   first_name  10 non-null     object
 2   last_name   10 non-null     object
dtypes: object(3)
memory usage: 320.0+ bytes

### Step 7. Merge all_data and data3 along the subject_id value

In [11]:
pd.merge(all_data, data3, on='subject_id')

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          4      Billy    Bonder       61
5          5     Ayoung   Atiches       16
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

In [12]:
data3_indexed = data3.set_index('subject_id')

all_data.join(data3_indexed, on='subject_id')

  subject_id first_name last_name  test_id
0          1       Alex  Anderson     51.0
1          2        Amy  Ackerman     15.0
2          3      Allen       Ali     15.0
3          4      Alice      Aoni     61.0
4          5     Ayoung   Atiches     16.0
0          4      Billy    Bonder     61.0
1          5      Brian     Black     16.0
2          6       Bran   Balwner      NaN
3          7      Bryce     Brice     14.0
4          8      Betty    Btisan     15.0

### Step 8. Merge only the data that has the same 'subject_id' on both data1 and data2

In [13]:
data1

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [14]:
data2

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [15]:
pd.merge(left= data1, right=data2, on='subject_id', how='inner')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Step 9. Merge all values in data1 and data2, with matching records from both sides where available.

In [16]:
pd.merge(data1, data2, on='subject_id', how='outer')

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan

In [17]:
### Merge v Join

In [18]:
df = pd.DataFrame({"name": ["A", "B", "C", "D"],
                   "city": ["NY", "LA", "CH", "BO"],
                   "age": [25, 30, 22, 34]})

df2 = pd.DataFrame({"name": ["A", "B", "C", "E"],
                   "city": ["NY", "LA", "CH", "BO"],
                   "salary": [4872, 7716, 6096, 3000]})

In [19]:
df

  name city  age
0    A   NY   25
1    B   LA   30
2    C   CH   22
3    D   BO   34

In [20]:
df2

  name city  salary
0    A   NY    4872
1    B   LA    7716
2    C   CH    6096
3    E   BO    3000

In [21]:
## Merge
how_types = ["left", "right", "inner", "outer"]

print("*"*20)
print(df)
print("-"*10)
print(df2)
print("*"*20)

for how_type in how_types:
    print("--> {}".format(how_type))
    print(pd.merge(df, df2, how=how_type))
    print("-"*20)

********************
  name city  age
0    A   NY   25
1    B   LA   30
2    C   CH   22
3    D   BO   34
----------
  name city  salary
0    A   NY    4872
1    B   LA    7716
2    C   CH    6096
3    E   BO    3000
********************
--> left
  name city  age  salary
0    A   NY   25  4872.0
1    B   LA   30  7716.0
2    C   CH   22  6096.0
3    D   BO   34     NaN
--------------------
--> right
  name city   age  salary
0    A   NY  25.0    4872
1    B   LA  30.0    7716
2    C   CH  22.0    6096
3    E   BO   NaN    3000
--------------------
--> inner
  name city  age  salary
0    A   NY   25    4872
1    B   LA   30    7716
2    C   CH   22    6096
--------------------
--> outer
  name city   age  salary
0    A   NY  25.0  4872.0
1    B   LA  30.0  7716.0
2    C   CH  22.0  6096.0
3    D   BO  34.0     NaN
4    E   BO   NaN  3000.0
--------------------

In [23]:
pd.merge(df, df2, on="name")

  name city_x  age city_y  salary
0    A     NY   25     NY    4872
1    B     LA   30     LA    7716
2    C     CH   22     CH    6096

In [24]:
pd.merge(df, df2, on="name", suffixes=["_u", "_v"])

  name city_u  age city_v  salary
0    A     NY   25     NY    4872
1    B     LA   30     LA    7716
2    C     CH   22     CH    6096

In [25]:
pd.merge(df, df2, on="name", suffixes=["_u", "_v"], how="left")

  name city_u  age city_v  salary
0    A     NY   25     NY  4872.0
1    B     LA   30     LA  7716.0
2    C     CH   22     CH  6096.0
3    D     BO   34    NaN     NaN

In [ ]:
## Join uses "Index" instead of common columns like in "Merge"!
## If you want to use desired columns for joining then
##    then we need to first create custome indices
how_types = ["left", "right", "inner", "outer"]

print("*"*20)
print(df)
print("-"*10)
print(df2)
print("*"*20)

for how_type in how_types:
    print("--> {}".format(how_type))
    print(df.join(df2, how=how_type))
    print("-"*20)

********************
  name city  age
0    A   NY   25
1    B   LA   30
2    C   CH   22
3    D   BO   34
----------
  name city  salary
0    A   NY    4872
1    B   LA    7716
2    C   CH    6096
3    E   BO    3000
********************
--> left

ValueError: columns overlap but no suffix specified: Index(['name', 'city'], dtype='object')