In [1]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

Soru 1: Verilen uçuş, müşteri ve kampanya bilgilerini içeren JSON dosyalarını alarak, müşteri ve uçuş bilgilerini left outer join ile, uçuş ve kampanya bilgilerini ise inner join ile birleştiriniz. Birleştirilen veri setinden, her müşterinin uçuş bilgilerini ve kampanya bilgilerini içeren anlamlı bir yapı oluşturunuz.

Soru 2: Birleştirilen veri setinden, son bir yıl içinde 1000 Euro üzerinde uçuş yapan müşterileri bulunuz ve her müşterinin toplam uçuş harcamalarını hesaplayınız.

Soru 3: Birleştirilen veri setinden, en yakın tarihte uçuş yapan 100 müşteriyi sıralayınız. Müşteriler, en yakın uçuş tarihinden en uzak tarihli uçuşa göre sıralanacaktır.

Soru 4: Müşteri ve uçuş verilerini merge kullanarak birleştiriniz. Merge işlemi sonrası, her müşterinin uçuş geçmişini ve kampanya bilgilerini içeren bir veri seti oluşturunuz.

Soru 5: LLM modelinin nasıl çalıştığı hakkında bir açıklama yapın ve özellikle dil modelinin, büyük veri kümeleriyle nasıl eğitim aldığını ve hangi durumlarda daha başarılı olduğunu tartışın.

soru:
Büyük veri kümeleri üzerinde dil modellerinin eğitimi hakkında konuşun. LLM (Large Language Model) kullanarak uçuş, müşteri ve kampanya verileri ile bir veri analizi yapmanızı istiyorum. Bu işlemde, farklı müşteri segmentlerinin uçuş davranışlarını tahmin etmek için uygun veri temizleme, özellik mühendisliği ve modelleme adımlarını belirleyin. Ayrıca, modelin performansını nasıl değerlendireceğinizi açıklayın.

In [2]:
campaigns_df = pd.read_json("campaigns.json")
flights_df = pd.read_json("flights.json")
customers_df = pd.read_json("customers.json")

In [3]:
campaigns_df.head()
#campaigns_df.set_index('CampaignID', inplace=True)
#campaigns_df.head(10)

   CampaignID     CampaignName  Discount
0          10      Summer Sale        15
1          11  Winter Discount        20
2          12     Spring Offer        10
3          13  Holiday Special        25
4          14   New Year Promo        30

In [4]:
#flights_df.set_index('FlightID', inplace=True)
flights_df.head(10)

   FlightID  CustomerID  FlightDate  FlightCost  CampaignID
0       101           1  2024-06-01        1200        10.0
1       102           2  2024-06-10         800        12.0
2       103           3  2024-04-20        1050        14.0
3       104           4  2024-03-15        1500        11.0
4       105           5  2024-02-05         500        15.0
5       999           6  2024-02-05         500         NaN

In [5]:
customers_df.head(10)

   CustomerID               Name  Country    JoinDate
0           1           John Doe      USA  2023-01-01
1           2         Jane Smith  Germany  2022-08-12
2           3         Samuel Lee   Canada  2023-05-22
3           4     Maria Gonzalez    Spain  2021-03-15
4           5        James Brown       UK  2020-07-30
5           6  Cansu Koken Citak       TR  2020-07-30

In [ ]:
customers_df.set_index("CustomerID").join(flights_df.set_index("CustomerID"), how='left')

In [ ]:
customer_flight = customers_df.set_index("CustomerID").join(flights_df.set_index("CustomerID"), how='left')

customer_flight.set_index("CampaignID").join(campaigns_df.set_index("CampaignID"), how='inner')

In [ ]:
bütün müşerilerin uçuş ve kampanya bilgileri

In [11]:
customer_flight_df = customers_df.set_index("CustomerID").join(flights_df.set_index("CustomerID"), how='left')
customer_flight_df.reset_index(inplace=True)

customer_flight_df.head(10)

,CustomerID,Name,Country,JoinDate,FlightID,FlightDate,FlightCost,CampaignID
0,1,John Doe,USA,2023-01-01,101,2024-06-01,1200,10.0
1,2,Jane Smith,Germany,2022-08-12,102,2024-06-10,800,12.0
2,3,Samuel Lee,Canada,2023-05-22,103,2024-04-20,1050,14.0
3,4,Maria Gonzalez,Spain,2021-03-15,104,2024-03-15,1500,11.0
4,5,James Brown,UK,2020-07-30,105,2024-02-05,500,15.0
5,6,Cansu Koken Citak,TR,2020-07-30,999,2024-02-05,500,NaN

In [13]:
cfc_df = customer_flight_df.set_index("CampaignID").join(campaigns_df.set_index("CampaignID"), how='left')
cfc_df.reset_index(inplace=True)

cfc_df.head(10)

,CampaignID,CustomerID,Name,Country,JoinDate,FlightID,FlightDate,FlightCost,CampaignName,Discount
0,10.0,1,John Doe,USA,2023-01-01,101,2024-06-01,1200,Summer Sale,15.0
1,12.0,2,Jane Smith,Germany,2022-08-12,102,2024-06-10,800,Spring Offer,10.0
2,14.0,3,Samuel Lee,Canada,2023-05-22,103,2024-04-20,1050,New Year Promo,30.0
3,11.0,4,Maria Gonzalez,Spain,2021-03-15,104,2024-03-15,1500,Winter Discount,20.0
4,15.0,5,James Brown,UK,2020-07-30,105,2024-02-05,500,Flash Sale,5.0
5,NaN,6,Cansu Koken Citak,TR,2020-07-30,999,2024-02-05,500,NaN,NaN

In [14]:
cfc_df[['Name', 'Country', 'CustomerID', 'FlightID', 'CampaignName', 'CampaignID']]

,Name,Country,CustomerID,FlightID,CampaignName,CampaignID
0,John Doe,USA,1,101,Summer Sale,10.0
1,Jane Smith,Germany,2,102,Spring Offer,12.0
2,Samuel Lee,Canada,3,103,New Year Promo,14.0
3,Maria Gonzalez,Spain,4,104,Winter Discount,11.0
4,James Brown,UK,5,105,Flash Sale,15.0
5,Cansu Koken Citak,TR,6,999,NaN,NaN

In [15]:
## uçuş tarihi en yakın 2 müşteri veya sıralaması

In [16]:
cfc_df.head(10)

,CampaignID,CustomerID,Name,Country,JoinDate,FlightID,FlightDate,FlightCost,CampaignName,Discount
0,10.0,1,John Doe,USA,2023-01-01,101,2024-06-01,1200,Summer Sale,15.0
1,12.0,2,Jane Smith,Germany,2022-08-12,102,2024-06-10,800,Spring Offer,10.0
2,14.0,3,Samuel Lee,Canada,2023-05-22,103,2024-04-20,1050,New Year Promo,30.0
3,11.0,4,Maria Gonzalez,Spain,2021-03-15,104,2024-03-15,1500,Winter Discount,20.0
4,15.0,5,James Brown,UK,2020-07-30,105,2024-02-05,500,Flash Sale,5.0
5,NaN,6,Cansu Koken Citak,TR,2020-07-30,999,2024-02-05,500,NaN,NaN

In [18]:
cfc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CampaignID    5 non-null      float64
 1   CustomerID    6 non-null      int64
 2   Name          6 non-null      object
 3   Country       6 non-null      object
 4   JoinDate      6 non-null      object
 5   FlightID      6 non-null      int64
 6   FlightDate    6 non-null      object
 7   FlightCost    6 non-null      int64
 8   CampaignName  5 non-null      object
 9   Discount      5 non-null      float64
dtypes: float64(2), int64(3), object(5)
memory usage: 608.0+ bytes

In [20]:
cfc_df['FlightDate'] = pd.to_datetime(cfc_df['FlightDate'])

cfc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CampaignID    5 non-null      float64
 1   CustomerID    6 non-null      int64
 2   Name          6 non-null      object
 3   Country       6 non-null      object
 4   JoinDate      6 non-null      object
 5   FlightID      6 non-null      int64
 6   FlightDate    6 non-null      datetime64[ns]
 7   FlightCost    6 non-null      int64
 8   CampaignName  5 non-null      object
 9   Discount      5 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 608.0+ bytes

In [26]:
cfc_df.sort_values(by='FlightDate', ascending=False).iloc[:2, :]

,CampaignID,CustomerID,Name,Country,JoinDate,FlightID,FlightDate,FlightCost,CampaignName,Discount
1,12.0,2,Jane Smith,Germany,2022-08-12,102,2024-06-10,800,Spring Offer,10.0
0,10.0,1,John Doe,USA,2023-01-01,101,2024-06-01,1200,Summer Sale,15.0

In [28]:
import pandas as pd
from datetime import datetime

# Örnek veriler (DataFrame'ler)
flights = pd.DataFrame({
    "FlightID": [101, 102, 103, 104, 105],
    "CustomerID": [1, 2, 3, 4, 5],
    "FlightDate": ["2024-06-01", "2024-06-10", "2024-04-20", "2024-03-15", "2024-02-05"],
    "FlightCost": [1200, 800, 1050, 1500, 500],
})

# Günümüz tarihini alıyoruz
current_date = datetime.now()

# FlightDate'i datetime formatına dönüştürüyoruz
flights['FlightDate'] = pd.to_datetime(flights['FlightDate'])

# Uçuş tarihine olan farkı hesaplıyoruz
flights['DateDifference'] = abs(flights['FlightDate'] - current_date)

# Tarihi en yakın olan iki müşteri
closest_flights = flights.nsmallest(2, 'DateDifference')

# Sonuçları yazdırıyoruz
print("Uçuş tarihi en yakın olan iki müşteri:")
print(closest_flights[['CustomerID', 'FlightDate', 'DateDifference']])

Uçuş tarihi en yakın olan iki müşteri:
   CustomerID FlightDate           DateDifference
1           2 2024-06-10 367 days 22:12:53.217095
0           1 2024-06-01 376 days 22:12:53.217095

### Ayni musterinin birden fazla kaydi oldugu durum

In [42]:
campaigns_df = pd.read_json("campaigns_updated.json")
flights_df = pd.read_json("flights_updated.json")
customers_df = pd.read_json("customers_updated.json")

In [43]:
campaigns_df

   CampaignID       CampaignName  Discount
0          10        Summer Sale        15
1          11    Winter Discount        20
2          12       Spring Offer        10
3          13    Holiday Special        25
4          14     New Year Promo        30
5          15         Flash Sale         5
6          16    Autumn Discount        18
7          17  Black Friday Sale        40

In [44]:
flights_df

   FlightID  CustomerID  FlightDate  FlightCost  CampaignID
0       101           1  2025-06-01        1200          10
1       102           2  2025-06-10         800          12
2       103           3  2025-04-20        1050          14
3       104           4  2025-03-15        1500          11
4       105           5  2025-02-05         500          15
5       106           1  2025-07-01        1300          13
6       107           2  2025-07-15         850          16
7       108           3  2025-05-01        1100          17
8       109           3  2021-05-01        1100          17

In [45]:
customers_df

   CustomerID               Name  Country    JoinDate
0           1           John Doe      USA  2023-01-01
1           2         Jane Smith  Germany  2022-08-12
2           3         Samuel Lee   Canada  2023-05-22
3           4     Maria Gonzalez    Spain  2021-03-15
4           5        James Brown       UK  2020-07-30
5           6  Cansu Koken Citak       TR  2020-07-30

In [41]:
## -->  Birleştirilen veri setinden, son bir yıl içinde 1000 Euro üzerinde uçuş yapan müşterileri bulunuz ve her müşterinin toplam uçuş harcamalarını hesaplayınız.

In [50]:
flights_df['FlightDate'] = pd.to_datetime(flights_df['FlightDate'])

now = pd.Timestamp.now()
year_before = pd.Timestamp(now.year - 1, now.month, now.day)


year_before_flights = flights_df[flights_df['FlightDate']  >= year_before]
year_before_flights

   FlightID  CustomerID FlightDate  FlightCost  CampaignID
0       101           1 2025-06-01        1200          10
1       102           2 2025-06-10         800          12
2       103           3 2025-04-20        1050          14
3       104           4 2025-03-15        1500          11
4       105           5 2025-02-05         500          15
5       106           1 2025-07-01        1300          13
6       107           2 2025-07-15         850          16
7       108           3 2025-05-01        1100          17

In [ ]:
groups = year_before_flights.groupby(by='CustomerID')

for name, group in groups:
    print(name)
    print(group)

    print('-'*10)

1
   FlightID  CustomerID FlightDate  FlightCost  CampaignID
0       101           1 2025-06-01        1200          10
5       106           1 2025-07-01        1300          13
----------
2
   FlightID  CustomerID FlightDate  FlightCost  CampaignID
1       102           2 2025-06-10         800          12
6       107           2 2025-07-15         850          16
----------
3
   FlightID  CustomerID FlightDate  FlightCost  CampaignID
2       103           3 2025-04-20        1050          14
7       108           3 2025-05-01        1100          17
----------
4
   FlightID  CustomerID FlightDate  FlightCost  CampaignID
3       104           4 2025-03-15        1500          11
----------
5
   FlightID  CustomerID FlightDate  FlightCost  CampaignID
4       105           5 2025-02-05         500          15
----------

In [58]:
cost_df = year_before_flights.groupby(by='CustomerID').sum('FlightCost')
cost_df

            FlightID  FlightCost  CampaignID
CustomerID
1                207        2500          23
2                209        1650          28
3                211        2150          31
4                104        1500          11
5                105         500          15

In [60]:
cost_df[cost_df['FlightCost'] > 1000]

            FlightID  FlightCost  CampaignID
CustomerID
1                207        2500          23
2                209        1650          28
3                211        2150          31
4                104        1500          11

In [61]:
year_before_flights

   FlightID  CustomerID FlightDate  FlightCost  CampaignID
0       101           1 2025-06-01        1200          10
1       102           2 2025-06-10         800          12
2       103           3 2025-04-20        1050          14
3       104           4 2025-03-15        1500          11
4       105           5 2025-02-05         500          15
5       106           1 2025-07-01        1300          13
6       107           2 2025-07-15         850          16
7       108           3 2025-05-01        1100          17

In [62]:
year_before_flights[year_before_flights['FlightCost'] > 1000]

   FlightID  CustomerID FlightDate  FlightCost  CampaignID
0       101           1 2025-06-01        1200          10
2       103           3 2025-04-20        1050          14
3       104           4 2025-03-15        1500          11
5       106           1 2025-07-01        1300          13
7       108           3 2025-05-01        1100          17

In [63]:
import pandas as pd
from datetime import datetime, timedelta

# Örnek veriler (güncellenmiş)
flights = pd.DataFrame({
    "FlightID": [101, 102, 103, 104, 105, 106, 107, 108],
    "CustomerID": [1, 2, 3, 4, 5, 1, 2, 3],
    "FlightDate": ["2024-06-01", "2024-06-10", "2024-04-20", "2024-03-15", "2024-02-05", "2024-07-01", "2024-07-15", "2024-05-01"],
    "FlightCost": [1200, 800, 1050, 1500, 500, 1300, 850, 1100],
    "CampaignID": [10, 12, 14, 11, 15, 13, 16, 17]
})

# Günümüz tarihi
current_date = datetime.now()

# Son bir yıl için tarih
one_year_ago = current_date - timedelta(days=365)

# Uçuş tarihini datetime formatına dönüştürüyoruz
flights['FlightDate'] = pd.to_datetime(flights['FlightDate'])

# Son bir yıl içindeki uçuşları filtreliyoruz
flights_last_year = flights[flights['FlightDate'] >= one_year_ago]

# 1000 Euro'nun üzerinde uçuş satın almış müşterileri buluyoruz
high_spender_customers = flights_last_year[flights_last_year['FlightCost'] > 1000]

# Müşteri başına toplam harcamayı hesaplıyoruz
total_spent = high_spender_customers.groupby('CustomerID')['FlightCost'].sum().reset_index()

# Sonuçları yazdırıyoruz
print("1000 Euro üzerinde uçuş yapan müşterilerin toplam harcamaları:")
print(total_spent)

1000 Euro üzerinde uçuş yapan müşterilerin toplam harcamaları:
   CustomerID  FlightCost
0           1        1300

In [64]:
year_before_flights

   FlightID  CustomerID FlightDate  FlightCost  CampaignID
0       101           1 2025-06-01        1200          10
1       102           2 2025-06-10         800          12
2       103           3 2025-04-20        1050          14
3       104           4 2025-03-15        1500          11
4       105           5 2025-02-05         500          15
5       106           1 2025-07-01        1300          13
6       107           2 2025-07-15         850          16
7       108           3 2025-05-01        1100          17

In [77]:
now = pd.Timestamp.now()

year_before_flights['DateDifference'] = now - year_before_flights['FlightDate']

year_before_flights.nsmallest(3, 'DateDifference')

C:\Users\citak\AppData\Local\Temp\ipykernel_20140\2129727199.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_before_flights['DateDifference'] = now - year_before_flights['FlightDate']

,FlightID,CustomerID,FlightDate,FlightCost,CampaignID,DateDifference
6,107,2,2025-07-15,850,16,-33 days +22:41:10.314668
5,106,1,2025-07-01,1300,13,-19 days +22:41:10.314668
1,102,2,2025-06-10,800,12,2 days 22:41:10.314668

In [81]:
year_before_flights[year_before_flights['FlightDate'] > now].nsmallest(15600, 'DateDifference')

,FlightID,CustomerID,FlightDate,FlightCost,CampaignID,DateDifference
6,107,2,2025-07-15,850,16,-33 days +22:41:10.314668
5,106,1,2025-07-01,1300,13,-19 days +22:41:10.314668

In [82]:
import pandas as pd
from datetime import datetime, timedelta

# Örnek veriler (güncellenmiş)
flights = pd.DataFrame({
    "FlightID": [101, 102, 103, 104, 105, 106, 107, 108],
    "CustomerID": [1, 2, 3, 4, 5, 1, 2, 3],
    "FlightDate": ["2024-06-01", "2024-06-10", "2024-04-20", "2024-03-15", "2024-02-05", "2024-07-01", "2024-07-15", "2024-05-01"],
    "FlightCost": [1200, 800, 1050, 1500, 500, 1300, 850, 1100],
    "CampaignID": [10, 12, 14, 11, 15, 13, 16, 17]
})

# Günümüz tarihi
current_date = datetime.now()

# Uçuş tarihini datetime formatına dönüştürüyoruz
flights['FlightDate'] = pd.to_datetime(flights['FlightDate'])

# 1000 Euro'nun üzerinde uçuş yapanları seçiyoruz
high_spender_customers = flights[flights['FlightCost'] > 1000]

# Henüz gerçekleşmemiş uçuşları (günümüzden sonraki uçuşları) filtreliyoruz
future_flights = high_spender_customers[high_spender_customers['FlightDate'] > current_date]

# En yakın iki uçuşu seçiyoruz
nearest_flights = future_flights.nsmallest(2, 'FlightDate')

# Sonuçları yazdırıyoruz
print("1000 Euro'nun üzerindeki uçuşlardan henüz gerçekleşmemiş en yakın iki uçuş:")
print(nearest_flights[['CustomerID', 'FlightID', 'FlightDate', 'FlightCost']])

1000 Euro'nun üzerindeki uçuşlardan henüz gerçekleşmemiş en yakın iki uçuş:
Empty DataFrame
Columns: [CustomerID, FlightID, FlightDate, FlightCost]
Index: []

In [83]:
## ucusuna 1 aydan az kalmis musteriler
year_before_flights

,FlightID,CustomerID,FlightDate,FlightCost,CampaignID,DateDifference
0,101,1,2025-06-01,1200,10,11 days 22:41:10.314668
1,102,2,2025-06-10,800,12,2 days 22:41:10.314668
2,103,3,2025-04-20,1050,14,53 days 22:41:10.314668
3,104,4,2025-03-15,1500,11,89 days 22:41:10.314668
4,105,5,2025-02-05,500,15,127 days 22:41:10.314668
5,106,1,2025-07-01,1300,13,-19 days +22:41:10.314668
6,107,2,2025-07-15,850,16,-33 days +22:41:10.314668
7,108,3,2025-05-01,1100,17,42 days 22:41:10.314668

In [94]:
year_before_flights[(year_before_flights['FlightDate'] > now)  & (year_before_flights['FlightDate'] < now  + timedelta(days=30))]

,FlightID,CustomerID,FlightDate,FlightCost,CampaignID,DateDifference
5,106,1,2025-07-01,1300,13,-19 days +22:41:10.314668

In [95]:
import pandas as pd
from datetime import datetime, timedelta

# Örnek veriler (güncellenmiş)
flights = pd.DataFrame({
    "FlightID": [101, 102, 103, 104, 105, 106, 107, 108],
    "CustomerID": [1, 2, 3, 4, 5, 1, 2, 3],
    "FlightDate": ["2024-06-01", "2024-06-10", "2024-04-20", "2024-03-15", "2024-02-05", "2024-07-01", "2024-07-15", "2024-05-01"],
    "FlightCost": [1200, 800, 1050, 1500, 500, 1300, 850, 1100],
    "CampaignID": [10, 12, 14, 11, 15, 13, 16, 17]
})

# Günümüz tarihi
current_date = datetime.now()

# Uçuş tarihini datetime formatına dönüştürüyoruz
flights['FlightDate'] = pd.to_datetime(flights['FlightDate'])

# Bir aydan az kalmış uçuşları bulmak için tarih farkını hesaplıyoruz
one_month_ahead = current_date + timedelta(days=30)

# Uçuş tarihi bir aydan az kalmış uçuşları seçiyoruz
flights_within_one_month = flights[(flights['FlightDate'] > current_date) & (flights['FlightDate'] <= one_month_ahead)]

# Sonuçları yazdırıyoruz
print("Bir aydan az kalmış uçuşları olan müşteriler:")
print(flights_within_one_month[['CustomerID', 'FlightID', 'FlightDate', 'FlightCost']])

Bir aydan az kalmış uçuşları olan müşteriler:
Empty DataFrame
Columns: [CustomerID, FlightID, FlightDate, FlightCost]
Index: []

### Soru4

In [96]:
campaigns_df = pd.read_json("campaigns_updated.json")
flights_df = pd.read_json("flights_updated.json")
customers_df = pd.read_json("customers_updated.json")

In [97]:
customers_df

   CustomerID               Name  Country    JoinDate
0           1           John Doe      USA  2023-01-01
1           2         Jane Smith  Germany  2022-08-12
2           3         Samuel Lee   Canada  2023-05-22
3           4     Maria Gonzalez    Spain  2021-03-15
4           5        James Brown       UK  2020-07-30
5           6  Cansu Koken Citak       TR  2020-07-30

In [98]:
flights_df

   FlightID  CustomerID  FlightDate  FlightCost  CampaignID
0       101           1  2025-06-01        1200          10
1       102           2  2025-06-10         800          12
2       103           3  2025-04-20        1050          14
3       104           4  2025-03-15        1500          11
4       105           5  2025-02-05         500          15
5       106           1  2025-07-01        1300          13
6       107           2  2025-07-15         850          16
7       108           3  2025-05-01        1100          17
8       109           3  2021-05-01        1100          17

In [101]:
cf_df = pd.merge(customers_df, flights_df, on='CustomerID')
cf_df

,CustomerID,Name,Country,JoinDate,FlightID,FlightDate,FlightCost,CampaignID
0,1,John Doe,USA,2023-01-01,101,2025-06-01,1200,10
1,1,John Doe,USA,2023-01-01,106,2025-07-01,1300,13
2,2,Jane Smith,Germany,2022-08-12,102,2025-06-10,800,12
3,2,Jane Smith,Germany,2022-08-12,107,2025-07-15,850,16
4,3,Samuel Lee,Canada,2023-05-22,103,2025-04-20,1050,14
5,3,Samuel Lee,Canada,2023-05-22,108,2025-05-01,1100,17
6,3,Samuel Lee,Canada,2023-05-22,109,2021-05-01,1100,17
7,4,Maria Gonzalez,Spain,2021-03-15,104,2025-03-15,1500,11
8,5,James Brown,UK,2020-07-30,105,2025-02-05,500,15

In [102]:
cfc_df = pd.merge(cf_df, campaigns_df, on='CampaignID')
cfc_df

,CustomerID,Name,Country,JoinDate,FlightID,FlightDate,FlightCost,CampaignID,CampaignName,Discount
0,1,John Doe,USA,2023-01-01,101,2025-06-01,1200,10,Summer Sale,15
1,1,John Doe,USA,2023-01-01,106,2025-07-01,1300,13,Holiday Special,25
2,2,Jane Smith,Germany,2022-08-12,102,2025-06-10,800,12,Spring Offer,10
3,2,Jane Smith,Germany,2022-08-12,107,2025-07-15,850,16,Autumn Discount,18
4,3,Samuel Lee,Canada,2023-05-22,103,2025-04-20,1050,14,New Year Promo,30
5,3,Samuel Lee,Canada,2023-05-22,108,2025-05-01,1100,17,Black Friday Sale,40
6,3,Samuel Lee,Canada,2023-05-22,109,2021-05-01,1100,17,Black Friday Sale,40
7,4,Maria Gonzalez,Spain,2021-03-15,104,2025-03-15,1500,11,Winter Discount,20
8,5,James Brown,UK,2020-07-30,105,2025-02-05,500,15,Flash Sale,5