# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data 

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [8]:
import os
import datetime
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

In [3]:
crime = pd.read_csv('US_Crime_Rates_1960_2014.csv')
crime.head(3)

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800

In [4]:
crime.shape

(55, 12)

### Step 4. What is the type of the columns?

In [5]:
crime.columns

Index(['Year', 'Population', 'Total', 'Violent', 'Property', 'Murder',
       'Forcible_Rape', 'Robbery', 'Aggravated_assault', 'Burglary',
       'Larceny_Theft', 'Vehicle_Theft'],
      dtype='object')

In [7]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     int64
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: int64(12)
memory usage: 5.3 KB

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [11]:
year_column = crime['Year']
year_column_datetime = pd.to_datetime(crime['Year'].astype('int64'), format='%Y')

crime['Year_datetime'] = year_column_datetime

crime.head(3)

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Year_datetime
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200,1960-01-01
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000,1961-01-01
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800,1962-01-01

In [12]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     int64
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
 12  Year_datetime       55 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(12)
memory usage: 5.7 KB

### Step 6. Set the Year column as the index of the dataframe

In [19]:
crime = crime.set_index('Year', drop = True)

crime.head(3)

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Year_datetime
Year,,,,,,,,,,,,
1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200,1960-01-01
1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000,1961-01-01
1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800,1962-01-01

### Step 7. Delete the Total column

In [25]:
crime.head(3)

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Year_datetime
Year,,,,,,,,,,,,
1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200,1960-01-01
1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000,1961-01-01
1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800,1962-01-01

In [29]:
crime.drop(columns=['Total'], inplace=True);

In [30]:
crime.head(3)

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Year_datetime
Year,,,,,,,,,,,
1960,179323175,288460,3095700,9110,17190,107840,154320,912100,1855400,328200,1960-01-01
1961,182992000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000,1961-01-01
1962,185771000,301510,3450700,8530,17550,110860,164570,994300,2089600,366800,1962-01-01

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

### Step 9. What is the most dangerous decade to live in the US?